name: dingleberries
favicon: null
layout_spectrum: 0.3373530553653836
typography_spectrum: 0.4684480580035597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.986331929685548
  lightness: 0.30442982725799084
  saturation: 0.08969913283362985
  rhythmicContrast: 0.011498071486130357
purpose: []
